予測したいレースに関連する馬をスクレイピングするコード

In [1]:
#インポート文
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.support.ui import Select,WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

import os
import time
import requests

In [2]:
dir = 'takamatsu/horsepage/2006'

In [3]:
urls = ['https://db.netkeiba.com/horse/1999110175/',
        'https://db.netkeiba.com/horse/2000102393/',
#         'https://db.netkeiba.com/horse/1999106907/',
#         'https://db.netkeiba.com/horse/2001103175/',
#         'https://db.netkeiba.com/horse/2002104192/',
#         'https://db.netkeiba.com/horse/1998107227/',
#         'https://db.netkeiba.com/horse/1999106730/',
#         'https://db.netkeiba.com/horse/1999100510/',
#         'https://db.netkeiba.com/horse/2002110074/',
#         'https://db.netkeiba.com/horse/1999102397/',
#         'https://db.netkeiba.com/horse/2000101550/',
#         'https://db.netkeiba.com/horse/2000106626/',
#         'https://db.netkeiba.com/horse/2000102386/',
#         'https://db.netkeiba.com/horse/2002100959/',
#         'https://db.netkeiba.com/horse/2000107407/',
#         'https://db.netkeiba.com/horse/2001107391/',
#         'https://db.netkeiba.com/horse/2000107264/',
#         'https://db.netkeiba.com/horse/2002106885/'
       ]

In [4]:
HTML_DIR = "html/"+dir
if not os.path.isdir(HTML_DIR):
    os.makedirs(HTML_DIR)
        
for url in urls:
    list = url.split("/")
    horse_id = list[-2]
    save_file_path = HTML_DIR+"/"+horse_id+'.html'
    response = requests.get(url)
    response.encoding = response.apparent_encoding
    html = response.text
    time.sleep(5)
    with open(save_file_path, 'w') as file:
        file.write(html)

In [5]:
horse_data_info_columns=[
    'horse_id',
    'bday',
    'tame_id',
    'owner_id',
    'producer_id',
    'production area',
    'auction price',
    'winnings',
    'lifetime record',
    'wined race title',
    'inbreeding-1',
    'inbreeding-2',
    'father',
    'faths father',
    'faths mother',
    'mother',
    'moths father',
    'moths mother'
]

In [6]:
horse_race_columns=["date",
                    "whereracecourse",
                    "weather",
                    "race_round",
                    "race_title",
                    "race_id",
                    "total_horse_number",
                    "frame_number",
                    "horse_number",
                    "odds",
                    "popular",
                    "rank",
                    "rider_id",
                    "horse_wight",
                    "distance",
                    "groud_status",
                    'goal_time',
                    'goal_time_dif',
                    'half_way_rank',
                    'pace',
                    'last_time',
                    'horse_weight',
                    'runner-up-horse-id',
                    'prize'
                    ]

In [7]:
def get_horse_data_by_html(horse_id, html):
    horse_list = [horse_id]
    horse_race_list = []
    soup = BeautifulSoup(html, 'html.parser')
    horse_tables = soup.find("table", class_="db_prof_table")
    horse_table = horse_tables.findAll("td")
    #for i in range(10):
    horse_list.append(horse_table[0].get_text())
    horse_list.append(horse_table[1].find('a').get('href').split("/")[-2])
    horse_list.append(horse_table[2].find('a').get('href').split("/")[-2])
    horse_list.append(horse_table[3].find('a').get('href').split("/")[-2])
    horse_list.append(horse_table[4].get_text())
    horse_list.append(horse_table[5].get_text())
    horse_list.append(horse_table[6].get_text())
    horse_list.append(horse_table[7].get_text())
    horse_list.append(horse_table[8].find('a').get('href').split("/")[-2])
    
    # horse_table[8]からすべてのリンクのURLの一部を取得する
    url_parts = [link.get('href').split("/")[-2] for link in horse_table[9].find_all('a')]

    # url_partsの要素数が2未満の場合、残りの要素をNaNで埋める
    while len(url_parts) < 2:
        url_parts.append(np.nan)

    # horse_listにurl_partsを追加する
    horse_list.extend(url_parts)
    
    #horse_list.append(horse_table[9].get_text())
    blood_tables = soup.find("table", class_="blood_table")
    blood_table = blood_tables.findAll("td")
    #for i in range(6):
    horse_list.append(blood_table[0].find('a').get('href').split("/")[-2])
    horse_list.append(blood_table[1].find('a').get('href').split("/")[-2])
    horse_list.append(blood_table[2].find('a').get('href').split("/")[-2])
    horse_list.append(blood_table[3].find('a').get('href').split("/")[-2])
    horse_list.append(blood_table[4].find('a').get('href').split("/")[-2])
    horse_list.append(blood_table[5].find('a').get('href').split("/")[-2])    
    
    
    
    
    
#horse_race
    horse_tables = soup.find("table", class_="db_h_race_results")
    horse_trs = horse_tables.findAll("tr")
    for index, horse_tr in enumerate(horse_trs):
        if index == 0:
            continue
        horse_tds = horse_tr.findAll("td")
        if horse_tds[26].find('a') is not None:
            horse_race_list.append([horse_tds[0].get_text(),
                                    horse_tds[1].get_text(),
                                    horse_tds[2].get_text(),
                                    horse_tds[3].get_text(),
                                    horse_tds[4].get_text(),
                                    horse_tds[4].find('a').get('href').split("/")[-2],
                                    horse_tds[6].get_text(),
                                    horse_tds[7].get_text(),
                                    horse_tds[8].get_text(),
                                    horse_tds[9].get_text(),
                                    horse_tds[10].get_text(),
                                    horse_tds[11].get_text(),
                                    horse_tds[12].find('a').get('href').split("/")[-2],
                                    horse_tds[13].get_text(),
                                    horse_tds[14].get_text(),
                                    horse_tds[15].get_text(),
                                    horse_tds[17].get_text(),
                                    horse_tds[18].get_text(),
                                    horse_tds[20].get_text(),
                                    horse_tds[21].get_text(),
                                    horse_tds[22].get_text(),
                                    horse_tds[23].get_text(),
                                    horse_tds[26].find('a').get('href').split("/")[-2],
                                    horse_tds[27].get_text(),
                                   ])
        else:
            horse_race_list.append([horse_tds[0].get_text(),
                                    horse_tds[1].get_text(),
                                    horse_tds[2].get_text(),
                                    horse_tds[3].get_text(),
                                    horse_tds[4].get_text(),
                                    horse_tds[4].find('a').get('href').split("/")[-2],
                                    horse_tds[6].get_text(),
                                    horse_tds[7].get_text(),
                                    horse_tds[8].get_text(),
                                    horse_tds[9].get_text(),
                                    horse_tds[10].get_text(),
                                    horse_tds[11].get_text(),
                                    horse_tds[12].find('a').get('href').split("/")[-2],
                                    horse_tds[13].get_text(),
                                    horse_tds[14].get_text(),
                                    horse_tds[15].get_text(),
                                    horse_tds[17].get_text(),
                                    horse_tds[18].get_text(),
                                    horse_tds[20].get_text(),
                                    horse_tds[21].get_text(),
                                    horse_tds[22].get_text(),
                                    horse_tds[23].get_text(),
                                    None,
                                    horse_tds[27].get_text(),
                                   ])
                                        
    horse_race_tmp_df = pd.DataFrame(horse_race_list, columns=horse_race_columns)
    horse_race_tmp_df.loc[:, 'horse_id'] = horse_id
    
    return horse_list , horse_race_tmp_df

In [9]:
CSV_DIR = "csv/"+dir
if not os.path.isdir(CSV_DIR):
    os.makedirs(CSV_DIR)
horse_info_csv = CSV_DIR+"/horse.csv"

horse_detail_df = pd.DataFrame(columns=horse_data_info_columns)
horse_race_df = pd.DataFrame()
if os.path.isdir(HTML_DIR):
    file_list = os.listdir(HTML_DIR)
    for file_name in file_list:
        with open(HTML_DIR+"/"+file_name, "r") as f:
            html = f.read()
            list = file_name.split(".")
            horse_id = list[-2]
            horse_list , horse_race_tmp_df = get_horse_data_by_html(horse_id, html) 
            horse_se = pd.Series(horse_list, index=horse_detail_df.columns)
            horse_detail_df = pd.concat([horse_detail_df, horse_se.to_frame().T], ignore_index=True)
            horse_race_df = pd.concat([horse_race_df, horse_race_tmp_df], axis=0, ignore_index=True)

In [10]:
horse_detail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   horse_id          2 non-null      object
 1   bday              2 non-null      object
 2   tame_id           2 non-null      object
 3   owner_id          2 non-null      object
 4   producer_id       2 non-null      object
 5   production area   2 non-null      object
 6   auction price     2 non-null      object
 7   winnings          2 non-null      object
 8   lifetime record   2 non-null      object
 9   wined race title  2 non-null      object
 10  inbreeding-1      2 non-null      object
 11  inbreeding-2      2 non-null      object
 12  father            2 non-null      object
 13  faths father      2 non-null      object
 14  faths mother      2 non-null      object
 15  mother            2 non-null      object
 16  moths father      2 non-null      object
 17  moths mother      2 non-null      object
dtypes: object(18)
memory usage: 416.0+ bytes

In [11]:
horse_race_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                90 non-null     object
 1   whereracecourse     90 non-null     object
 2   weather             90 non-null     object
 3   race_round          90 non-null     object
 4   race_title          90 non-null     object
 5   race_id             90 non-null     object
 6   total_horse_number  90 non-null     object
 7   frame_number        90 non-null     object
 8   horse_number        90 non-null     object
 9   odds                90 non-null     object
 10  popular             90 non-null     object
 11  rank                90 non-null     object
 12  rider_id            90 non-null     object
 13  horse_wight         90 non-null     object
 14  distance            90 non-null     object
 15  groud_status        90 non-null     object
 16  goal_time           90 non-null     object
 17  goal_time_dif       90 non-null     object
 18  half_way_rank       90 non-null     object
 19  pace                90 non-null     object
 20  last_time           90 non-null     object
 21  horse_weight        90 non-null     object
 22  runner-up-horse-id  89 non-null     object
 23  prize               90 non-null     object
 24  horse_id            90 non-null     object
dtypes: object(25)
memory usage: 17.7+ KB

### cleaning

##### horse_race

In [17]:
horse_detail_df

,horse_id,bday,tame_id,owner_id,producer_id,production area,auction price,winnings,lifetime record,wined race title,inbreeding-1,inbreeding-2,father,faths father,faths mother,mother,moths father,moths mother
0,1999110175,1999年2月17日,00427,951005,200879,米,\n-\n,"\n\n\n\n2億9,725万円 (中央) /403万円 (地方)\n",52戦8勝 [8-4-3-37],200408020411,000a006643,,000a002161,000a001607,000a00ada1,000a00a808,000a0012cb,000a00a807
1,2000102393,2000年6月3日,00390,078800,910082,静内町,\n-\n,"\n\n\n\n2億3,405万円 (中央) /810万円 (地方)\n",38戦11勝 [11-3-4-20],200504030711,2005100670,1997102415,000a00025e,000a0010a8,000a0093ef,1992102137,000a000249,1980100896

##### date

In [16]:
horse_race_df

,date,whereracecourse,weather,race_round,race_title,race_id,total_horse_number,frame_number,horse_number,odds,...,groud_status,goal_time,goal_time_dif,half_way_rank,pace,last_time,horse_weight,runner-up-horse-id,prize,horse_id
0,2008-08-15,笠松,晴,6,葉月特別,200847081506,6,3,3,1.9,...,良,1:42.9,-0.1,2-2-2,,,486(0),2002100157,43.0,1999110175
1,2008-07-18,名古屋,晴,11,名港盃(G),200848071811,12,3,3,11.1,...,重,2:08.8,4.6,6-8-8,,43.4,486(+2),2004104654,,1999110175
2,2007-05-27,2中京4,晴,4,障害3歳以上未勝利,200707020404,14,8,13,7.3,...,良,3:05.2,3.3,1-1-2-3,107.0-39.2,13.2,484(-2),2002106706,210.0,1999110175
3,2007-03-25,1中京8,晴,11,高松宮記念(G1),200707010811,18,3,6,228.7,...,重,1:10.3,1.4,15-13,33.8-35.1,35.5,486(0),2002107011,,1999110175
4,2007-03-04,1阪神4,晴,4,障害4歳以上未勝利,200709010404,14,2,2,5.0,...,良,3:22.7,3.2,3-4-5-3,108.0-40.6,13.6,486(-2),2003104060,85.0,1999110175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2003-12-21,5阪神6,晴,9,高砂特別(1000万下),200309050609,15,2,3,16.3,...,良,1:26.4,1.7,3-3,34.5-38.1,39.4,504(0),2000102789,,2000102393
86,2003-11-30,4東京8,曇,4,3歳以上500万下,200305040804,16,6,12,7.1,...,不,1:25.3,-0.3,5-3,34.9-37.9,37.8,504(-7),1999106970,750.0,2000102393
87,2003-09-10,船橋,晴,9,ナティーホイップ特別,200343091009,13,6,8,,...,良,1:41.9,-1.2,6-7-5-5,37.6-38.8,38.4,511(+3),2000101199,300.0,2000102393
88,2003-07-06,2福島6,曇,3,3歳未勝利,200303020603,14,7,12,4.2,...,良,1:49.6,1.6,8-5-4-2,30.5-39.0,40.4,508(+4),2000103679,50.0,2000102393
89,2003-06-22,2福島2,晴,5,3歳未勝利,200303020205,14,7,12,12.8,...,良,1:48.3,1.2,4-3-2-1,29.8-39.0,40.1,504(0),2000107574,130.0,2000102393

In [14]:
horse_race_df['date'] = pd.to_datetime(horse_race_df['date'], format='%Y/%m/%d')

In [15]:
horse_race_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                90 non-null     datetime64[ns]
 1   whereracecourse     90 non-null     object
 2   weather             90 non-null     object
 3   race_round          90 non-null     object
 4   race_title          90 non-null     object
 5   race_id             90 non-null     object
 6   total_horse_number  90 non-null     object
 7   frame_number        90 non-null     object
 8   horse_number        90 non-null     object
 9   odds                90 non-null     object
 10  popular             90 non-null     object
 11  rank                90 non-null     object
 12  rider_id            90 non-null     object
 13  horse_wight         90 non-null     object
 14  distance            90 non-null     object
 15  groud_status        90 non-null     object
 16  goal_time           90 non-null     object
 17  goal_time_dif       90 non-null     object
 18  half_way_rank       90 non-null     object
 19  pace                90 non-null     object
 20  last_time           90 non-null     object
 21  horse_weight        90 non-null     object
 22  runner-up-horse-id  89 non-null     object
 23  prize               90 non-null     object
 24  horse_id            90 non-null     object
dtypes: datetime64[ns](1), object(24)
memory usage: 17.7+ KB

In [ ]:
# horse_detail_df['horse_id'] = horse_detail_df['horse_id']
# horse_detail_df['tame_id'] = horse_detail_df['tame_id']
# horse_detail_df['owner_id'] = horse_detail_df['owner_id']

#以下文字列の可能性あり
# horse_detail_df['inbreeding-1'] = horse_detail_df['inbreeding-1']
# horse_detail_df['inbreeding-2'] = horse_detail_df['inbreeding-2']
# horse_detail_df['father'] = horse_detail_df['father']
# horse_detail_df['mother'] = horse_detail_df['mother']

In [ ]:
# # データを読み込む
# data = pd.read_csv('data.csv')

# # 日付でソートする
# data = data.sort_values('date')

# # 同じ ID を持つデータをグループ化する
# grouped_data = data.groupby('ID')

# # 各グループの最初のデータを選択する
# latest_data = grouped_data.last()

In [ ]:
horse_detail_df.to_csv(horse_info_csv, header=True, index=False)