In [61]:
#pip install google-cloud-bigquery これ必要
#pip install pydata_google_auth
#pip install db-dtypes

In [87]:
#インポート文
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import lightgbm as lgb
from lightgbm import LGBMRanker

from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold

from sklearn.metrics import confusion_matrix

import optuna

import pydata_google_auth
from google.cloud import bigquery 

import pickle

In [88]:
credentials = pydata_google_auth.get_user_credentials(
    ['https://www.googleapis.com/auth/bigquery'],
)

In [89]:
client = bigquery.Client(project='keiba-381006', credentials=credentials)

In [90]:
race_query = '''
    SELECT * 
    FROM osaka.race_table
    '''
race_df = client.query(race_query).to_dataframe()

In [91]:
pd.set_option('display.max_columns', 100)
race_df.head(1)

,race_id,race_round,race_title,weather,ground_status,date,where_racecourse,total_horse_number,frame_number_first,horse_number_first,frame_number_second,horse_number_second,frame_number_third,horse_number_third,tansyo,hukusyo_first,hukusyo_second,hukusyo_third,wakuren,umaren,wide_1_2,wide_1_3,wide_2_3,umatan,renhuku3,rentan3,is_obstacle,ground_type,is_left_right_straight,distance,datetime
0,201709020411,11,第61回大阪杯(G1),0,1,2017-04-02,9,14,4,5,3,4,8,13,240,110,280,280,2130,2320,540,480,1800,3390,4830,23910,0,1,1,2000,2017-04-02 15:40:00+00:00

In [92]:
horse_query = '''
    SELECT * 
    FROM osaka.horse_table 
    '''
horse_df = client.query(horse_query).to_dataframe()

In [93]:
pd.set_option('display.max_columns', 100)
horse_df.head(1)

,race_id,rank,frame_number,horse_number,horse_id,burden_weight,rider_id,goal_time,goal_time_dif,half_way_rank,last_time,odds,popular,horse_weight,tamer_id,owner_id,is_down,age,sex,horse_weight_dif,burden_weight_rate,avg_velocity
0,202009020411,2,8,12,2016104750,55,1102,118.4,0.0,3.0,34,5.2,4,454,1151,226800,0,4,1,-6,0.121145,16.891892

In [94]:
horse_info_query = '''
    SELECT * 
    FROM osaka.horse_info_table
    '''
horse_info_df = client.query(horse_info_query).to_dataframe()

In [95]:
pd.set_option('display.max_columns', 100)
horse_info_df.head(1)

,horse_id,bday,tame_id,owner_id,producer_id,production_area,auction_price,winnings,lifetime_record,wined_race_title,inbreeding_1,inbreeding_2,father,faths_father,faths_mother,mother,moths_father,moths_mother
0,2012104463,2012年3月17日,01128,471033,393126,千歳市,928万円 (2014年 千葉サラブレッド・セール),"2億3,061万円 (中央)",59戦9勝 [9-8-5-37],201803020811,2011104480,0,2003102205,000a000d77,1997102385,2004103210,1998101516,000a00fa62

In [96]:
horse_race_query = '''
    SELECT * 
    FROM osaka.horse_race_table
    '''
horse_race_df = client.query(horse_race_query).to_dataframe()

In [97]:
pd.set_option('display.max_columns', 100)
horse_race_df.head(1)

,date,where_racecourse,weather,race_round,race_title,race_id,total_horse_number,frame_number,horse_number,odds,popular,rank,rider_id,burden_weight,distance,ground_status,goal_time,goal_time_dif,half_way_rank,pace,last_time,horse_weight,runner_up_horse_id,prize,horse_id,target_race_id,race_rank,horse_weight_dif,ground_type,race_date
0,2014-11-01,8,1,9,萩S(OP),201408040809,6,4,4,5.8,3,5,1018,55.0,1800,1,1:48.0,0.4,6-6,35.9-34.8,34.3,448,2012105703,150.0,2012104463,201809020411,0,0,1,2018-04-01

In [98]:
targetrace_query = '''
    SELECT * 
    FROM osaka.targetrace_table
    '''
targetrace_df = client.query(targetrace_query).to_dataframe()

In [99]:
pd.set_option('display.max_columns', 100)
targetrace_df.head(1)

,race_id,race_title,date,race_round,weather,ground_status,where_racecourse,total_horse_number,race_rank,is_obstacle,ground_type,is_left_right_straight,distance,datetime
0,202309020411,大阪杯(G1),2023-04-02,11,0,1,9,16,3,0,1,1,2000,2023-04-02 15:40:00+00:00

In [100]:
targethorse_query = '''
    SELECT * 
    FROM osaka.targethorse_table
    '''
targethorse_df = client.query(targethorse_query).to_dataframe()

In [101]:
pd.set_option('display.max_columns', 100)
targethorse_df.head(1)

,race_id,frame_number,horse_number,horse_id,burden_weight,rider_id,tamer_id,horse_weight,odds,popular,horse_name,age,sex,horse_weight_dif,burden_weight_rate
0,202309020411,1,1,2018105081,56,1174,1151,472,None,None,ジェラルディーナ,5,1,2,0.118644

In [102]:
targethorse_info_query = '''
    SELECT * 
    FROM osaka.targethorse_info_table
    '''
targethorse_info_df = client.query(targethorse_info_query).to_dataframe()

In [103]:
pd.set_option('display.max_columns', 100)
targethorse_info_df.head(1)

,horse_id,bday,tame_id,owner_id,producer_id,production_area,lifetime_record,wined_race_title,inbreeding_1,inbreeding_2,father,faths_father,faths_mother,mother,moths_father,moths_mother
0,2018100927,2018年4月6日,1101,708800,803320,日高町,18戦5勝 [5-4-3-6],202210040211,2019102071,2.020102e+09,1998110135,000a00013a,000a000071,2012104864,2002100816,2006103348

In [104]:
targethorse_race_query = '''
    SELECT * 
    FROM osaka.targethorse_race_table
    '''
targethorse_race_df = client.query(targethorse_race_query).to_dataframe()

In [105]:
pd.set_option('display.max_columns', 100)
targethorse_race_df.head(1)

,date,where_racecourse,weather,race_round,race_title,race_id,total_horse_number,frame_number,horse_number,odds,popular,rank,rider_id,burden_weight,distance,ground_status,goal_time,goal_time_dif,half_way_rank,pace,last_time,horse_weight,runner_up_horse_id,horse_id,race_rank,horse_weight_dif,ground_type
0,2019-10-26,8,0,9,萩S(L),201908040809,7,4,4,2.2,1,1,5271,55.0,1800,3,1:50.8,-0.1,3-3,37.5-34.7,34.5,490,2.017105e+09,2017105567,0,0,1

In [106]:
horse_columns = ['rank',
                         'race_id',
                          'horse_id',
                          'rider_id',
                          'horse_number',
                          'age',
                          'sex',
#                           'odds',
#                           'popular',
                          'horse_weight'
                         ]
targethorse_columns = [
                         'race_id',
                          'horse_id',
                          'rider_id',
                          'horse_number',
                          'age',
                          'sex',
#                           'odds',
#                           'popular',
                          'horse_weight'
                         ]
df_main = horse_df[horse_columns]
df_target = targethorse_df[targethorse_columns]

In [107]:
#データのマージ
df_tmp_1 = race_df[['race_id',
                      'ground_status',
                     ]]
df_main_1 = pd.merge(df_main, df_tmp_1, on='race_id', how='left')

df_tmp_1 = targetrace_df[['race_id',
                      'ground_status',
                     ]]
df_target_1 = pd.merge(df_target, df_tmp_1, on='race_id', how='left')

In [108]:
# データのマージ
df_tmp_2 = horse_info_df[['horse_id',
                       'tame_id',
                       'inbreeding_1',
                       'inbreeding_2'
                     ]]
#重複データの削除
df_tmp_2 = df_tmp_2.drop_duplicates(subset=['horse_id'])

df_main_2 = pd.merge(df_main_1, df_tmp_2, on='horse_id', how='left')

df_tmp_2 = targethorse_info_df[['horse_id',
                       'tame_id',
                       'inbreeding_1',
                       'inbreeding_2'
                     ]]

df_target_2 = pd.merge(df_target_1, df_tmp_2, on='horse_id', how='left')

In [109]:
df_main_2

,rank,race_id,horse_id,rider_id,horse_number,age,sex,horse_weight,ground_status,tame_id,inbreeding_1,inbreeding_2
0,2,202009020411,2016104750,1102,12,4,1,454,1,01151,202006050811,0
1,1,202109020411,2017105335,1088,8,4,1,422,4,01117,202109020411,0
2,8,202209020411,2018105554,1014,11,4,1,498,1,01151,202109020609,0
3,4,201709020411,2013105788,5339,14,4,0,502,1,01061,2010104042,2016104415
4,7,201709020411,2013106099,1018,1,4,0,480,1,01002,2015105013,2011104074
...,...,...,...,...,...,...,...,...,...,...,...,...
80,7,202209020411,2015101654,1124,15,7,2,468,1,01028,2017106602,2010100697
81,9,201809020411,2010102459,700,6,8,1,474,1,01058,2014104273,2007100100
82,10,201709020411,2009102678,700,9,8,0,500,1,01013,2007105728,2008105790
83,15,201809020411,2010103602,732,10,8,0,510,1,01071,2014102878,2004102759
84,14,202209020411,2013105788,1174,16,9,0,510,1,01061,2010104042,2016104415

In [110]:
df_target_2

,race_id,horse_id,rider_id,horse_number,age,sex,horse_weight,ground_status,tame_id,inbreeding_1,inbreeding_2
0,202309020411,2018105081,1174,1,5,1,472,1,1151,202209050411,NaN
1,202309020411,2018100927,1115,2,5,1,428,1,1101,2019102071,2.020102e+09
2,202309020411,2019104740,5339,11,4,1,484,1,1118,202205021011,NaN
3,202309020411,2016100915,1171,3,7,0,498,1,1142,2014100870,2.020106e+09
4,202309020411,2018102348,5203,4,5,0,488,1,1145,2020105998,2.017102e+09
5,202309020411,2018105074,1018,5,5,0,472,1,1129,2019105240,2.020103e+09
6,202309020411,2017105567,1088,6,6,0,498,1,1071,202307010611,NaN
7,202309020411,2019102879,660,7,4,0,476,1,1044,2009101399,2.015102e+09
8,202309020411,2019101782,5386,8,4,0,494,1,420,2020101712,NaN
9,202309020411,2018100274,666,9,5,0,512,1,1062,2019101507,2.014102e+09
10,202309020411,2017105376,1163,10,6,0,472,1,1061,2012104669,2.013106e+09
11,202309020411,2019105155,1180,12,4,0,474,1,1151,202106050911,NaN
12,202309020411,2018104963,1140,13,5,0,530,1,438,2016104435,2.017105e+09
13,202309020411,2016104877,1126,14,7,0,486,1,1070,2013106138,2.012105e+09
14,202309020411,2016104851,1032,15,7,2,466,1,1151,202310020411,NaN
15,202309020411,2018100420,1102,16,5,0,478,1,1058,2017100404,2.020102e+09

##### ラベルエンコーディング

In [111]:
#df_target_2['horse_weight'] = df_target_2['horse_weight'].astype(float)

In [112]:
df_target_2['rank']=0

In [113]:
df_merged = pd.concat([df_target_2, df_main_2], axis=0)

In [114]:
le = LabelEncoder()
df_merged = pd.concat([df_target_2, df_main_2], axis=0)

In [115]:
# tame_id = le.fit(df_merged['tame_id'])
# df_main_2['tame_id'] = le.transform(df_main_2['tame_id'])
# df_target_2['tame_id'] = le.transform(df_target_2['tame_id'])

# inbreeding_1 = le.fit(df_merged['inbreeding_1'])
# df_main_2['inbreeding_1'] = le.transform(df_main_2['inbreeding_1'])
# df_target_2['inbreeding_1'] = le.transform(df_target_2['inbreeding_1'])

# inbreeding_2 = le.fit(df_merged['inbreeding_2'])
# df_main_2['inbreeding_2'] = le.transform(df_main_2['inbreeding_2'])
# df_target_2['inbreeding_2'] = le.transform(df_target_2['inbreeding_2'])

In [116]:
df_main_2['rank'] = df_main_2['rank'].astype('int64')
df_main_2['race_id'] = df_main_2['race_id'].astype('int64')
df_main_2['horse_id'] = df_main_2['horse_id'].astype('int64')
df_main_2['rider_id'] = df_main_2['rider_id'].astype('int64')
df_main_2['horse_number'] = df_main_2['horse_number'].astype('int64')
df_main_2['age'] = df_main_2['age'].astype('int64')
df_main_2['sex'] = df_main_2['sex'].astype('int64')
# df_main_2['popular'] = df_main_2['popular'].astype('int64')
df_main_2['ground_status'] = df_main_2['ground_status'].astype('int64')

In [117]:
df_target_2['rank'] = df_target_2['rank'].astype('int64')
df_target_2['race_id'] = df_target_2['race_id'].astype('int64')
df_target_2['horse_id'] = df_target_2['horse_id'].astype('int64')
df_target_2['rider_id'] = df_target_2['rider_id'].astype('int64')
df_target_2['horse_number'] = df_target_2['horse_number'].astype('int64')
df_target_2['age'] = df_target_2['age'].astype('int64')
df_target_2['sex'] = df_target_2['sex'].astype('int64')
# df_target_2['popular'] = df_target_2['popular'].astype('int64')
df_target_2['ground_status'] = df_target_2['ground_status'].astype('int64')

In [118]:
#使う特徴量の設定
id = {"race_id",
      "horse_id"
    }

feature = [
           "race_id",
           "horse_id",
           "rider_id",
           "horse_number",
           "age",
           "sex",
#             "odds",
#             'popular',
            'horse_weight',
            'ground_status',
#             'tame_id',
#             'inbreeding_1',
#             'inbreeding_2'
            ]

target = ['rank']

X_id = df_main_2[feature]
X_id['horse_weight'] = X_id['horse_weight'].astype('int64')
# X_id['tame_id'] = X_id['tame_id'].astype('int64')
# X_id['inbreeding_1'] = X_id['inbreeding_1'].astype('int64')
y = df_main_2[target]

C:\Users\kawam\AppData\Local\Temp\ipykernel_2276\1755405370.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_id['horse_weight'] = X_id['horse_weight'].astype('int64')

In [119]:
X_id.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85 entries, 0 to 84
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   race_id        85 non-null     int64
 1   horse_id       85 non-null     int64
 2   rider_id       85 non-null     int64
 3   horse_number   85 non-null     int64
 4   age            85 non-null     int64
 5   sex            85 non-null     int64
 6   horse_weight   85 non-null     int64
 7   ground_status  85 non-null     int64
dtypes: int64(8)
memory usage: 6.0 KB

In [120]:
#使う特徴量の設定
id = {"race_id",
      "horse_id"
    }

feature = [
           "race_id",
           "horse_id",
           "rider_id",
           "horse_number",
           "age",
           "sex",
#             "odds",
#             'popular',
            'horse_weight',
            'ground_status',
#             'tame_id',
#             'inbreeding_1',
#             'inbreeding_2'
            ]

target = ['rank']

today_race_X = df_target_2[feature]
today_race_X['horse_weight'] = today_race_X['horse_weight'].astype('int64')
# today_race_X['tame_id'] = today_race_X['tame_id'].astype('int64')
# today_race_X['inbreeding_1'] = today_race_X['inbreeding_1'].astype('int64')
today_race_X.to_csv("../data/main/today.csv",index=False)

C:\Users\kawam\AppData\Local\Temp\ipykernel_2276\1324036470.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  today_race_X['horse_weight'] = today_race_X['horse_weight'].astype('int64')

In [121]:
today_race_X_with_name = pd.merge(today_race_X, targethorse_df[['horse_id', 'horse_name']], on='horse_id', how='left')
today_race_X.to_csv("../data/main/today_withname.csv",index=False)

In [122]:
pred_df = pd.DataFrame()
#スコア結果を入れるリスト
reports = []
auc_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
support_scores = []

#予測結果を入れるリスト
pred_df_list = []

def objective(trial):
    
# Optuna
    # ハイパーパラメータの探索範囲
    params = {
        'boosting_type': 'gbdt',
        'num_leaves': trial.suggest_int('num_leaves', 10, 100),
        'learning_rate': trial.suggest_float('learning_rate', 1e-4, 1e-1),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.1, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 1, 10),
        'lambda_l1': trial.suggest_float('lambda_l1', 1e-8, 10.0),
        'lambda_l2': trial.suggest_float('lambda_l2', 1e-8, 10.0),
        'verbose': -1
    }
    
    #LGBMRankerの設定
    ranker = LGBMRanker(**params)

# K-fold
    #kflodの設定
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)

    #kflodで学習用と検証用に分ける
    for fold, (train_idx, val_idx) in enumerate(kfold.split(X_id, y)):
        #id入りの学習データ
        X_train_id, X_val_id = X_id.iloc[train_idx], X_id.iloc[val_idx]
        
        #id抜きの学習データ
        X = X_id.drop(id, axis =1)
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        
        #検証データ
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

# Fit
        # train_basketsを計算
        train_baskets = X_train_id.groupby(["race_id"])["horse_id"].count().values

        # モデルの学習
        model = ranker.fit(X_train,
                           y_train,
                           group=train_baskets)

# Predict
        # モデルの予測
        y_pred = model.predict(X_val)

        #結果を入れるデータフレームを用意
        pred_df_fold = pd.DataFrame({
           "race_id": X_val_id['race_id'],
           "horse_id": X_val_id['horse_id'],
           "rank":y_val['rank'],
           "pred": y_pred
           })

        #そのデータフレームをリストに保存
        pred_df_list.append(pred_df_fold)

# Rank
    # 各foldの予測結果を結合してpred_dfを作成
    pred_df = pd.concat(pred_df_list, axis=0).reset_index(drop=True)

    #予測した結果をrace_idごとでグループ化し順位をつける
    pred_df['pred_rank'] = pred_df.groupby('race_id')['pred'].rank(method='min', ascending=False)

    #3位以内ならprizeを1にする
    pred_df['rank_prize'] = pred_df['rank'].apply(lambda x: 1 if x <= 3 else 0)
    pred_df['pred_rank_prize'] = pred_df['pred_rank'].apply(lambda x: 1 if x <= 3 else 0)
    print(pred_df)

#Score
    #正確度を計算
    auc_score = metrics.accuracy_score(pred_df['rank_prize'], pred_df['pred_rank_prize'])
        
    #auc_scoresのリストに保存
    auc_scores.append(auc_score)
    
    #f1を計算            
    f1 = f1_score(pred_df['rank_prize'], pred_df['pred_rank_prize'])
    
    #reportを計算
    report = metrics.classification_report(pred_df['rank_prize'], pred_df['pred_rank_prize'])
    report_num = metrics.precision_recall_fscore_support(pred_df['rank_prize'], pred_df['pred_rank_prize'])
    reports.append(report)

    #reportから情報をとる
    precision_scores.append(report_num[0])
    recall_scores.append(report_num[1])
    f1_scores.append(report_num[2])
    support_scores.append(report_num[3])
    
    return f1

In [123]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)

[I 2023-04-03 11:11:50,880] A new study created in memory with name: no-name-41a184d9-596c-4629-b0b3-d549b1c37c75

[LightGBM] [Warning] feature_fraction is set=0.3609105280654197, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3609105280654197
[LightGBM] [Warning] lambda_l1 is set=0.6488857894952603, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.6488857894952603
[LightGBM] [Warning] bagging_fraction is set=0.6892859258720874, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6892859258720874
[LightGBM] [Warning] lambda_l2 is set=7.331240378842017, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.331240378842017
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.3609105280654197, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3609105280654197
[LightGBM] [Warning] lambda_l1 is set=0.6488857894952603, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.6488857894952603
[LightGBM] [Warning] bagging_fraction is set=0.6892859258720874, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6892859258720874
[LightGBM] [Warning] lambda_l2 is set=7.331240378842017, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.331240378842017
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.3609105280654197, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3609105280654197
[LightGBM] [Warning] lambda_l1 is set=0.6488857894952603, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.6488857894952603
[LightGBM] [Warning] bagging_fraction is set=0.6892859258720874, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6892859258720874
[LightGBM] [Warning] lambda_l2 is set=7.331240378842017, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.331240378842017
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.3609105280654197, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3609105280654197
[LightGBM] [Warning] lambda_l1 is set=0.6488857894952603, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.6488857894952603
[LightGBM] [Warning] bagging_fraction is set=0.6892859258720874, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6892859258720874
[LightGBM] [Warning] lambda_l2 is set=7.331240378842017, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.331240378842017
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.3609105280654197, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.3609105280654197
[LightGBM] [Warning] lambda_l1 is set=0.6488857894952603, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.6488857894952603
[LightGBM] [Warning] bagging_fraction is set=0.6892859258720874, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6892859258720874
[LightGBM] [Warning] lambda_l2 is set=7.331240378842017, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.331240378842017
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2

[I 2023-04-03 11:11:51,258] Trial 0 finished with value: 0.1111111111111111 and parameters: {'num_leaves': 40, 'learning_rate': 0.09788728257678926, 'feature_fraction': 0.3609105280654197, 'bagging_fraction': 0.6892859258720874, 'bagging_freq': 2, 'lambda_l1': 0.6488857894952603, 'lambda_l2': 7.331240378842017}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.4756764647657389, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4756764647657389
[LightGBM] [Warning] lambda_l1 is set=0.24354248389439523, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24354248389439523
[LightGBM] [Warning] bagging_fraction is set=0.4684018671587006, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4684018671587006
[LightGBM] [Warning] lambda_l2 is set=2.4743356715029536, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.4743356715029536
[LightGBM] [Warning] bagging_freq is set=10, subsample_freq=0 will be ignored. Current value: bagging_freq=10
[LightGBM] [Warning] feature_fraction is set=0.4756764647657389, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4756764647657389
[LightGBM] [Warning] lambda_l1 is set=0.24354248389439523, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24354248389439523
[LightGBM] [Warning] bagging_fraction is set=0.4684018671587006, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4684018671587006
[LightGBM] [Warning] lambda_l2 is set=2.4743356715029536, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.4743356715029536
[LightGBM] [Warning] bagging_freq is set=10, subsample_freq=0 will be ignored. Current value: bagging_freq=10
[LightGBM] [Warning] feature_fraction is set=0.4756764647657389, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4756764647657389
[LightGBM] [Warning] lambda_l1 is set=0.24354248389439523, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24354248389439523
[LightGBM] [Warning] bagging_fraction is set=0.4684018671587006, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4684018671587006
[LightGBM] [Warning] lambda_l2 is set=2.4743356715029536, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.4743356715029536
[LightGBM] [Warning] bagging_freq is set=10, subsample_freq=0 will be ignored. Current value: bagging_freq=10
[LightGBM] [Warning] feature_fraction is set=0.4756764647657389, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4756764647657389
[LightGBM] [Warning] lambda_l1 is set=0.24354248389439523, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24354248389439523
[LightGBM] [Warning] bagging_fraction is set=0.4684018671587006, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4684018671587006
[LightGBM] [Warning] lambda_l2 is set=2.4743356715029536, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.4743356715029536
[LightGBM] [Warning] bagging_freq is set=10, subsample_freq=0 will be ignored. Current value: bagging_freq=10
[LightGBM] [Warning] feature_fraction is set=0.4756764647657389, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4756764647657389
[LightGBM] [Warning] lambda_l1 is set=0.24354248389439523, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24354248389439523
[LightGBM] [Warning] bagging_fraction is set=0.4684018671587006, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4684018671587006
[LightGBM] [Warning] lambda_l2 is set=2.4743356715029536, reg_lambda=0.0 will be ignored. Current value: lambda_l2=2.4743356715029536
[LightGBM] [Warning] bagging_freq is set=10, subsample_freq=0 will be ignored. Current value: bagging_freq=10

[I 2023-04-03 11:11:51,608] Trial 1 finished with value: 0.1090909090909091 and parameters: {'num_leaves': 62, 'learning_rate': 0.07729598081396245, 'feature_fraction': 0.4756764647657389, 'bagging_fraction': 0.4684018671587006, 'bagging_freq': 10, 'lambda_l1': 0.24354248389439523, 'lambda_l2': 2.4743356715029536}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.5687594751413045, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5687594751413045
[LightGBM] [Warning] lambda_l1 is set=9.07671949166787, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.07671949166787
[LightGBM] [Warning] bagging_fraction is set=0.43641932832299035, subsample=1.0 will be ignored. Current value: bagging_fraction=0.43641932832299035
[LightGBM] [Warning] lambda_l2 is set=0.9592305580394391, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.9592305580394391
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5687594751413045, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5687594751413045
[LightGBM] [Warning] lambda_l1 is set=9.07671949166787, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.07671949166787
[LightGBM] [Warning] bagging_fraction is set=0.43641932832299035, subsample=1.0 will be ignored. Current value: bagging_fraction=0.43641932832299035
[LightGBM] [Warning] lambda_l2 is set=0.9592305580394391, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.9592305580394391
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5687594751413045, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5687594751413045
[LightGBM] [Warning] lambda_l1 is set=9.07671949166787, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.07671949166787
[LightGBM] [Warning] bagging_fraction is set=0.43641932832299035, subsample=1.0 will be ignored. Current value: bagging_fraction=0.43641932832299035
[LightGBM] [Warning] lambda_l2 is set=0.9592305580394391, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.9592305580394391
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5687594751413045, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5687594751413045
[LightGBM] [Warning] lambda_l1 is set=9.07671949166787, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.07671949166787
[LightGBM] [Warning] bagging_fraction is set=0.43641932832299035, subsample=1.0 will be ignored. Current value: bagging_fraction=0.43641932832299035
[LightGBM] [Warning] lambda_l2 is set=0.9592305580394391, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.9592305580394391
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5687594751413045, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5687594751413045
[LightGBM] [Warning] lambda_l1 is set=9.07671949166787, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.07671949166787
[LightGBM] [Warning] bagging_fraction is set=0.43641932832299035, subsample=1.0 will be ignored. Current value: bagging_fraction=0.43641932832299035
[LightGBM] [Warning] lambda_l2 is set=0.9592305580394391, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.9592305580394391
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8

[I 2023-04-03 11:11:51,965] Trial 2 finished with value: 0.0821917808219178 and parameters: {'num_leaves': 62, 'learning_rate': 0.08373635423971819, 'feature_fraction': 0.5687594751413045, 'bagging_fraction': 0.43641932832299035, 'bagging_freq': 8, 'lambda_l1': 9.07671949166787, 'lambda_l2': 0.9592305580394391}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.5328118487072097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5328118487072097
[LightGBM] [Warning] lambda_l1 is set=3.0121351046031664, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.0121351046031664
[LightGBM] [Warning] bagging_fraction is set=0.6495608215830497, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6495608215830497
[LightGBM] [Warning] lambda_l2 is set=4.60456052035491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.60456052035491
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5328118487072097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5328118487072097
[LightGBM] [Warning] lambda_l1 is set=3.0121351046031664, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.0121351046031664
[LightGBM] [Warning] bagging_fraction is set=0.6495608215830497, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6495608215830497
[LightGBM] [Warning] lambda_l2 is set=4.60456052035491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.60456052035491
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5328118487072097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5328118487072097
[LightGBM] [Warning] lambda_l1 is set=3.0121351046031664, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.0121351046031664
[LightGBM] [Warning] bagging_fraction is set=0.6495608215830497, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6495608215830497
[LightGBM] [Warning] lambda_l2 is set=4.60456052035491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.60456052035491
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5328118487072097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5328118487072097
[LightGBM] [Warning] lambda_l1 is set=3.0121351046031664, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.0121351046031664
[LightGBM] [Warning] bagging_fraction is set=0.6495608215830497, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6495608215830497
[LightGBM] [Warning] lambda_l2 is set=4.60456052035491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.60456052035491
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8
[LightGBM] [Warning] feature_fraction is set=0.5328118487072097, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5328118487072097
[LightGBM] [Warning] lambda_l1 is set=3.0121351046031664, reg_alpha=0.0 will be ignored. Current value: lambda_l1=3.0121351046031664
[LightGBM] [Warning] bagging_fraction is set=0.6495608215830497, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6495608215830497
[LightGBM] [Warning] lambda_l2 is set=4.60456052035491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.60456052035491
[LightGBM] [Warning] bagging_freq is set=8, subsample_freq=0 will be ignored. Current value: bagging_freq=8

[I 2023-04-03 11:11:52,333] Trial 3 finished with value: 0.06593406593406594 and parameters: {'num_leaves': 28, 'learning_rate': 0.04679967304391197, 'feature_fraction': 0.5328118487072097, 'bagging_fraction': 0.6495608215830497, 'bagging_freq': 8, 'lambda_l1': 3.0121351046031664, 'lambda_l2': 4.60456052035491}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.48807484614483543, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48807484614483543
[LightGBM] [Warning] lambda_l1 is set=9.822164145205576, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.822164145205576
[LightGBM] [Warning] bagging_fraction is set=0.7776702297034791, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7776702297034791
[LightGBM] [Warning] lambda_l2 is set=0.36838120770379396, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.36838120770379396
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.48807484614483543, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48807484614483543
[LightGBM] [Warning] lambda_l1 is set=9.822164145205576, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.822164145205576
[LightGBM] [Warning] bagging_fraction is set=0.7776702297034791, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7776702297034791
[LightGBM] [Warning] lambda_l2 is set=0.36838120770379396, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.36838120770379396
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.48807484614483543, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48807484614483543
[LightGBM] [Warning] lambda_l1 is set=9.822164145205576, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.822164145205576
[LightGBM] [Warning] bagging_fraction is set=0.7776702297034791, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7776702297034791
[LightGBM] [Warning] lambda_l2 is set=0.36838120770379396, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.36838120770379396
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.48807484614483543, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48807484614483543
[LightGBM] [Warning] lambda_l1 is set=9.822164145205576, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.822164145205576
[LightGBM] [Warning] bagging_fraction is set=0.7776702297034791, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7776702297034791
[LightGBM] [Warning] lambda_l2 is set=0.36838120770379396, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.36838120770379396
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.48807484614483543, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.48807484614483543

[I 2023-04-03 11:11:52,717] Trial 4 finished with value: 0.05504587155963303 and parameters: {'num_leaves': 16, 'learning_rate': 0.06902286049522925, 'feature_fraction': 0.48807484614483543, 'bagging_fraction': 0.7776702297034791, 'bagging_freq': 1, 'lambda_l1': 9.822164145205576, 'lambda_l2': 0.36838120770379396}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] lambda_l1 is set=9.822164145205576, reg_alpha=0.0 will be ignored. Current value: lambda_l1=9.822164145205576
[LightGBM] [Warning] bagging_fraction is set=0.7776702297034791, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7776702297034791
[LightGBM] [Warning] lambda_l2 is set=0.36838120770379396, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.36838120770379396
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.6077854380183872, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6077854380183872
[LightGBM] [Warning] lambda_l1 is set=4.860194889031501, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.860194889031501
[LightGBM] [Warning] bagging_fraction is set=0.5445786431676681, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5445786431676681
[LightGBM] [Warning] lambda_l2 is set=7.44435289532885, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.44435289532885
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.6077854380183872, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6077854380183872
[LightGBM] [Warning] lambda_l1 is set=4.860194889031501, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.860194889031501
[LightGBM] [Warning] bagging_fraction is set=0.5445786431676681, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5445786431676681
[LightGBM] [Warning] lambda_l2 is set=7.44435289532885, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.44435289532885
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.6077854380183872, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6077854380183872
[LightGBM] [Warning] lambda_l1 is set=4.860194889031501, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.860194889031501
[LightGBM] [Warning] bagging_fraction is set=0.5445786431676681, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5445786431676681
[LightGBM] [Warning] lambda_l2 is set=7.44435289532885, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.44435289532885
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.6077854380183872, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6077854380183872
[LightGBM] [Warning] lambda_l1 is set=4.860194889031501, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.860194889031501
[LightGBM] [Warning] bagging_fraction is set=0.5445786431676681, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5445786431676681
[LightGBM] [Warning] lambda_l2 is set=7.44435289532885, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.44435289532885
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.6077854380183872, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6077854380183872
[LightGBM] [Warning] lambda_l1 is set=4.860194889031501, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.860194889031501
[LightGBM] [Warning] bagging_fraction is set=0.5445786431676681, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5445786431676681
[LightGBM] [Warning] lambda_l2 is set=7.44435289532885, reg_lambda=0.0 will be ignored. Current value: lambda_l2=7.44435289532885
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

[I 2023-04-03 11:11:53,130] Trial 5 finished with value: 0.047244094488188976 and parameters: {'num_leaves': 51, 'learning_rate': 0.08868324920808571, 'feature_fraction': 0.6077854380183872, 'bagging_fraction': 0.5445786431676681, 'bagging_freq': 5, 'lambda_l1': 4.860194889031501, 'lambda_l2': 7.44435289532885}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.5422911963691048, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5422911963691048
[LightGBM] [Warning] lambda_l1 is set=4.011233888754746, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.011233888754746
[LightGBM] [Warning] bagging_fraction is set=0.4450831597762611, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4450831597762611
[LightGBM] [Warning] lambda_l2 is set=1.9315330516925031, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.9315330516925031
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] feature_fraction is set=0.5422911963691048, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5422911963691048
[LightGBM] [Warning] lambda_l1 is set=4.011233888754746, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.011233888754746
[LightGBM] [Warning] bagging_fraction is set=0.4450831597762611, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4450831597762611
[LightGBM] [Warning] lambda_l2 is set=1.9315330516925031, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.9315330516925031
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] feature_fraction is set=0.5422911963691048, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5422911963691048
[LightGBM] [Warning] lambda_l1 is set=4.011233888754746, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.011233888754746
[LightGBM] [Warning] bagging_fraction is set=0.4450831597762611, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4450831597762611
[LightGBM] [Warning] lambda_l2 is set=1.9315330516925031, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.9315330516925031
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] feature_fraction is set=0.5422911963691048, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5422911963691048
[LightGBM] [Warning] lambda_l1 is set=4.011233888754746, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.011233888754746
[LightGBM] [Warning] bagging_fraction is set=0.4450831597762611, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4450831597762611
[LightGBM] [Warning] lambda_l2 is set=1.9315330516925031, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.9315330516925031
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] feature_fraction is set=0.5422911963691048, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5422911963691048
[LightGBM] [Warning] lambda_l1 is set=4.011233888754746, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.011233888754746
[LightGBM] [Warning] bagging_fraction is set=0.4450831597762611, subsample=1.0 will be ignored. Current value: bagging_fraction=0.4450831597762611
[LightGBM] [Warning] lambda_l2 is set=1.9315330516925031, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.9315330516925031
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3

[I 2023-04-03 11:11:53,579] Trial 6 finished with value: 0.041379310344827586 and parameters: {'num_leaves': 17, 'learning_rate': 0.09828257495851164, 'feature_fraction': 0.5422911963691048, 'bagging_fraction': 0.4450831597762611, 'bagging_freq': 3, 'lambda_l1': 4.011233888754746, 'lambda_l2': 1.9315330516925031}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.5102640865999212, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5102640865999212
[LightGBM] [Warning] lambda_l1 is set=4.220458555707753, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.220458555707753
[LightGBM] [Warning] bagging_fraction is set=0.7144729594447333, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7144729594447333
[LightGBM] [Warning] lambda_l2 is set=0.6178638336780473, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.6178638336780473
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5102640865999212, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5102640865999212
[LightGBM] [Warning] lambda_l1 is set=4.220458555707753, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.220458555707753
[LightGBM] [Warning] bagging_fraction is set=0.7144729594447333, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7144729594447333
[LightGBM] [Warning] lambda_l2 is set=0.6178638336780473, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.6178638336780473
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5102640865999212, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5102640865999212
[LightGBM] [Warning] lambda_l1 is set=4.220458555707753, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.220458555707753
[LightGBM] [Warning] bagging_fraction is set=0.7144729594447333, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7144729594447333
[LightGBM] [Warning] lambda_l2 is set=0.6178638336780473, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.6178638336780473
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6

[I 2023-04-03 11:11:53,995] Trial 7 finished with value: 0.03680981595092024 and parameters: {'num_leaves': 44, 'learning_rate': 0.0716242701639229, 'feature_fraction': 0.5102640865999212, 'bagging_fraction': 0.7144729594447333, 'bagging_freq': 6, 'lambda_l1': 4.220458555707753, 'lambda_l2': 0.6178638336780473}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.5102640865999212, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5102640865999212
[LightGBM] [Warning] lambda_l1 is set=4.220458555707753, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.220458555707753
[LightGBM] [Warning] bagging_fraction is set=0.7144729594447333, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7144729594447333
[LightGBM] [Warning] lambda_l2 is set=0.6178638336780473, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.6178638336780473
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5102640865999212, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5102640865999212
[LightGBM] [Warning] lambda_l1 is set=4.220458555707753, reg_alpha=0.0 will be ignored. Current value: lambda_l1=4.220458555707753
[LightGBM] [Warning] bagging_fraction is set=0.7144729594447333, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7144729594447333
[LightGBM] [Warning] lambda_l2 is set=0.6178638336780473, reg_lambda=0.0 will be ignored. Current value: lambda_l2=0.6178638336780473
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.1846359958318573, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1846359958318573
[LightGBM] [Warning] lambda_l1 is set=7.195855824722982, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.195855824722982
[LightGBM] [Warning] bagging_fraction is set=0.8439715972511203, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8439715972511203
[LightGBM] [Warning] lambda_l2 is set=4.768257943704529, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.768257943704529
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.1846359958318573, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1846359958318573
[LightGBM] [Warning] lambda_l1 is set=7.195855824722982, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.195855824722982
[LightGBM] [Warning] bagging_fraction is set=0.8439715972511203, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8439715972511203
[LightGBM] [Warning] lambda_l2 is set=4.768257943704529, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.768257943704529
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.1846359958318573, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1846359958318573
[LightGBM] [Warning] lambda_l1 is set=7.195855824722982, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.195855824722982
[LightGBM] [Warning] bagging_fraction is set=0.8439715972511203, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8439715972511203
[LightGBM] [Warning] lambda_l2 is set=4.768257943704529, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.768257943704529
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.1846359958318573, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1846359958318573
[LightGBM] [Warning] lambda_l1 is set=7.195855824722982, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.195855824722982
[LightGBM] [Warning] bagging_fraction is set=0.8439715972511203, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8439715972511203
[LightGBM] [Warning] lambda_l2 is set=4.768257943704529, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.768257943704529
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.1846359958318573, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1846359958318573
[LightGBM] [Warning] lambda_l1 is set=7.195855824722982, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.195855824722982
[LightGBM] [Warning] bagging_fraction is set=0.8439715972511203, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8439715972511203
[LightGBM] [Warning] lambda_l2 is set=4.768257943704529, reg_lambda=0.0 will be ignored. Current value: lambda_l2=4.768257943704529
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5

[I 2023-04-03 11:11:54,359] Trial 8 finished with value: 0.03314917127071823 and parameters: {'num_leaves': 82, 'learning_rate': 0.019809575286596992, 'feature_fraction': 0.1846359958318573, 'bagging_fraction': 0.8439715972511203, 'bagging_freq': 5, 'lambda_l1': 7.195855824722982, 'lambda_l2': 4.768257943704529}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.8146338736375555, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8146338736375555
[LightGBM] [Warning] lambda_l1 is set=7.834929099963112, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.834929099963112
[LightGBM] [Warning] bagging_fraction is set=0.19083683406582136, subsample=1.0 will be ignored. Current value: bagging_fraction=0.19083683406582136
[LightGBM] [Warning] lambda_l2 is set=9.072801618047455, reg_lambda=0.0 will be ignored. Current value: lambda_l2=9.072801618047455
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.8146338736375555, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8146338736375555
[LightGBM] [Warning] lambda_l1 is set=7.834929099963112, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.834929099963112
[LightGBM] [Warning] bagging_fraction is set=0.19083683406582136, subsample=1.0 will be ignored. Current value: bagging_fraction=0.19083683406582136
[LightGBM] [Warning] lambda_l2 is set=9.072801618047455, reg_lambda=0.0 will be ignored. Current value: lambda_l2=9.072801618047455
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.8146338736375555, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8146338736375555
[LightGBM] [Warning] lambda_l1 is set=7.834929099963112, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.834929099963112
[LightGBM] [Warning] bagging_fraction is set=0.19083683406582136, subsample=1.0 will be ignored. Current value: bagging_fraction=0.19083683406582136
[LightGBM] [Warning] lambda_l2 is set=9.072801618047455, reg_lambda=0.0 will be ignored. Current value: lambda_l2=9.072801618047455
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.8146338736375555, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8146338736375555
[LightGBM] [Warning] lambda_l1 is set=7.834929099963112, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.834929099963112
[LightGBM] [Warning] bagging_fraction is set=0.19083683406582136, subsample=1.0 will be ignored. Current value: bagging_fraction=0.19083683406582136
[LightGBM] [Warning] lambda_l2 is set=9.072801618047455, reg_lambda=0.0 will be ignored. Current value: lambda_l2=9.072801618047455
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

[I 2023-04-03 11:11:54,728] Trial 9 finished with value: 0.030150753768844223 and parameters: {'num_leaves': 95, 'learning_rate': 0.03717744750566459, 'feature_fraction': 0.8146338736375555, 'bagging_fraction': 0.19083683406582136, 'bagging_freq': 4, 'lambda_l1': 7.834929099963112, 'lambda_l2': 9.072801618047455}. Best is trial 0 with value: 0.1111111111111111.

[LightGBM] [Warning] feature_fraction is set=0.8146338736375555, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8146338736375555
[LightGBM] [Warning] lambda_l1 is set=7.834929099963112, reg_alpha=0.0 will be ignored. Current value: lambda_l1=7.834929099963112
[LightGBM] [Warning] bagging_fraction is set=0.19083683406582136, subsample=1.0 will be ignored. Current value: bagging_fraction=0.19083683406582136
[LightGBM] [Warning] lambda_l2 is set=9.072801618047455, reg_lambda=0.0 will be ignored. Current value: lambda_l2=9.072801618047455
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

Empty DataFrame
Columns: []
Index: []

In [39]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_bagging_fraction,params_bagging_freq,params_feature_fraction,params_lambda_l1,params_lambda_l2,params_learning_rate,params_num_leaves,state
0,0,0.349515,2023-04-03 10:50:07.582138,2023-04-03 10:50:07.965945,0 days 00:00:00.383807,0.585436,2,0.156979,2.325107,5.676945,0.033766,25,COMPLETE
1,1,0.349515,2023-04-03 10:50:07.968955,2023-04-03 10:50:08.319392,0 days 00:00:00.350437,0.320001,9,0.264730,9.801557,4.733025,0.083147,27,COMPLETE
2,2,0.349515,2023-04-03 10:50:08.323383,2023-04-03 10:50:08.666177,0 days 00:00:00.342794,0.343851,1,0.810194,7.322466,0.827629,0.090353,47,COMPLETE
3,3,0.349515,2023-04-03 10:50:08.669705,2023-04-03 10:50:08.994282,0 days 00:00:00.324577,0.248648,10,0.600972,5.284350,0.103727,0.051751,85,COMPLETE
4,4,0.349515,2023-04-03 10:50:08.998283,2023-04-03 10:50:09.355267,0 days 00:00:00.356984,0.449727,10,0.708036,6.011968,8.344377,0.012887,40,COMPLETE
5,5,0.349515,2023-04-03 10:50:09.359268,2023-04-03 10:50:09.683416,0 days 00:00:00.324148,0.947709,2,0.928949,5.438477,6.865997,0.068037,99,COMPLETE
6,6,0.349515,2023-04-03 10:50:09.687426,2023-04-03 10:50:10.139816,0 days 00:00:00.452390,0.338056,9,0.905180,9.798040,3.948333,0.074378,81,COMPLETE
7,7,0.349515,2023-04-03 10:50:10.142988,2023-04-03 10:50:10.498873,0 days 00:00:00.355885,0.212456,8,0.760420,9.632818,1.970283,0.051728,35,COMPLETE
8,8,0.349515,2023-04-03 10:50:10.503391,2023-04-03 10:50:10.851253,0 days 00:00:00.347862,0.565260,2,0.464057,8.649886,2.932731,0.066411,16,COMPLETE
9,9,0.274157,2023-04-03 10:50:10.854259,2023-04-03 10:50:11.216490,0 days 00:00:00.362231,0.915008,10,0.831211,2.246128,4.735461,0.042510,70,COMPLETE

In [40]:
#Optunaによる、ベストパラメータの取得
best_params = study.best_params

In [41]:
best_ranker = LGBMRanker(**best_params)

In [42]:
train_baskets = X_id.groupby(["race_id"])["horse_id"].count().values
X = X_id.drop(id, axis =1)
model = best_ranker.fit(X,
                        y,
                        group=train_baskets)

[LightGBM] [Warning] feature_fraction is set=0.1569790432774512, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1569790432774512
[LightGBM] [Warning] lambda_l1 is set=2.3251072452925223, reg_alpha=0.0 will be ignored. Current value: lambda_l1=2.3251072452925223
[LightGBM] [Warning] bagging_fraction is set=0.585436339402936, subsample=1.0 will be ignored. Current value: bagging_fraction=0.585436339402936
[LightGBM] [Warning] lambda_l2 is set=5.676945342954598, reg_lambda=0.0 will be ignored. Current value: lambda_l2=5.676945342954598
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2

In [43]:
result = model.predict(X)

In [44]:
with open('model.pickle', 'wb') as f:
    pickle.dump(model, f)

In [45]:
#predict
train_baskets = X_id.groupby(["race_id"])["horse_id"].count().values
X = X_id.drop(["race_id", "horse_id"], axis=1)
y_pred = model.predict(X, group=train_baskets)

# 結果を入れるデータフレームを用意
pred_df = pd.DataFrame({
   "race_id": X_id['race_id'],
   "horse_id": X_id['horse_id'],
   "rank": y['rank'],
   "pred": y_pred
})

#予測した結果をrace_idごとでグループ化し順位をつける
pred_df['pred_rank'] = pred_df.groupby('race_id')['pred'].rank(method='min', ascending=False)

#3位以内ならprizeを1にする
pred_df['rank_prize'] = pred_df['rank'].apply(lambda x: 1 if x <= 3 else 0)
pred_df['pred_rank_prize'] = pred_df['pred_rank'].apply(lambda x: 1 if x <= 3 else 0)

In [46]:
pred_df

,race_id,horse_id,rank,pred,pred_rank,rank_prize,pred_rank_prize
0,202009020411,2016104750,2,0.0,1.0,1,1
1,202109020411,2017105335,1,0.0,1.0,1,1
2,202209020411,2018105554,8,0.0,1.0,0,1
3,201709020411,2013105788,4,0.0,1.0,0,1
4,201709020411,2013106099,7,0.0,1.0,0,1
...,...,...,...,...,...,...,...
80,202209020411,2015101654,7,0.0,1.0,0,1
81,201809020411,2010102459,9,0.0,1.0,0,1
82,201709020411,2009102678,10,0.0,1.0,0,1
83,201809020411,2010103602,15,0.0,1.0,0,1
84,202209020411,2013105788,14,0.0,1.0,0,1

In [47]:
#predict
train_baskets = today_race_X.groupby(["race_id"])["horse_id"].count().values
X = today_race_X.drop(["race_id", "horse_id"], axis=1)
y_pred = model.predict(X, group=train_baskets)

# 結果を入れるデータフレームを用意
pred_df = pd.DataFrame({
   "race_id": today_race_X['race_id'],
   "horse_id": today_race_X['horse_id'],
    "horse_name":today_race_X_with_name['horse_name'],
        "horse_number":today_race_X['horse_number'],
   "pred": y_pred
})

#予測した結果をrace_idごとでグループ化し順位をつける
pred_df['pred_rank'] = pred_df.groupby('race_id')['pred'].rank(method='min', ascending=False)

#3位以内ならprizeを1にする
pred_df['pred_rank_prize'] = pred_df['pred_rank'].apply(lambda x: 1 if x <= 3 else 0)

In [48]:
pred_df.sort_values('horse_number')

,race_id,horse_id,horse_name,horse_number,pred,pred_rank,pred_rank_prize
0,202309020411,2018105081,ジェラルディーナ,1,0.0,1.0,1
1,202309020411,2018100927,マリアエレーナ,2,0.0,1.0,1
3,202309020411,2016100915,モズベッロ,3,0.0,1.0,1
4,202309020411,2018102348,ノースブリッジ,4,0.0,1.0,1
5,202309020411,2018105074,ワンダフルタウン,5,0.0,1.0,1
6,202309020411,2017105567,ェルトライゼンデ,6,0.0,1.0,1
7,202309020411,2019102879,マテンロウレオ,7,0.0,1.0,1
8,202309020411,2019101782,ラーグルフ,8,0.0,1.0,1
9,202309020411,2018100274,ジャックドール,9,0.0,1.0,1
10,202309020411,2017105376,ポタジェ,10,0.0,1.0,1
2,202309020411,2019104740,スターズオンアース,11,0.0,1.0,1
11,202309020411,2019105155,キラーアビリティ,12,0.0,1.0,1
12,202309020411,2018104963,ダノンザキッド,13,0.0,1.0,1
13,202309020411,2016104877,ヒシイグアス,14,0.0,1.0,1
14,202309020411,2016104851,ヒンドゥタイムズ,15,0.0,1.0,1
15,202309020411,2018100420,ノースザワールド,16,0.0,1.0,1

In [49]:
# Unpickle model
model = pd.read_pickle('./model.pickle')

In [50]:
# one = float(request.POST.get('one'))
# two = float(request.POST.get('two'))
# three = float(request.POST.get('three'))
# four = float(request.POST.get('four'))
# five = float(request.POST.get('five'))
# six = float(request.POST.get('six'))
# seven = float(request.POST.get('seven'))
# eight = float(request.POST.get('eight'))
# nine = float(request.POST.get('nine'))
# ten = float(request.POST.get('ten'))
# eleven = float(request.POST.get('eleven'))
# twelve = float(request.POST.get('twelve'))
# thirteen = float(request.POST.get('thirteen'))
# fourteen = float(request.POST.get('fourteen'))
# fifteen = float(request.POST.get('fifteen'))
# sixteen = float(request.POST.get('sixteen'))
# seventeen = float(request.POST.get('seventeen'))
# eighteen = float(request.POST.get('eighteen'))

In [51]:
one = 500
two = 500
three = 500
four = 500
five = 500
six = 500
seven = 500
eight = 500
nine = 500
ten = 500
eleven = 500
twelve = 500
thirteen = 500
fourteen = 500
fifteen = 500
sixteen = 500
# seventeen = 500
# eighteen = 500

In [52]:
today_race_X = pd.read_csv('../data/main/today.csv')
today_race_X_withname = pd.read_csv('../data/main/today_withname.csv')

In [53]:
today_race_X.loc[today_race_X['horse_number'] == 1, 'horse_weight'] = one
today_race_X.loc[today_race_X['horse_number'] == 2, 'horse_weight'] = two
today_race_X.loc[today_race_X['horse_number'] == 3, 'horse_weight'] = three
today_race_X.loc[today_race_X['horse_number'] == 4, 'horse_weight'] = four
today_race_X.loc[today_race_X['horse_number'] == 5, 'horse_weight'] = five
today_race_X.loc[today_race_X['horse_number'] == 6, 'horse_weight'] = six
today_race_X.loc[today_race_X['horse_number'] == 7, 'horse_weight'] = seven
today_race_X.loc[today_race_X['horse_number'] == 8, 'horse_weight'] = eight
today_race_X.loc[today_race_X['horse_number'] == 9, 'horse_weight'] = nine
today_race_X.loc[today_race_X['horse_number'] == 10, 'horse_weight'] = ten
today_race_X.loc[today_race_X['horse_number'] == 11, 'horse_weight'] = eleven
today_race_X.loc[today_race_X['horse_number'] == 12, 'horse_weight'] = twelve
today_race_X.loc[today_race_X['horse_number'] == 13, 'horse_weight'] = thirteen
today_race_X.loc[today_race_X['horse_number'] == 14, 'horse_weight'] = fourteen
today_race_X.loc[today_race_X['horse_number'] == 15, 'horse_weight'] = fifteen
today_race_X.loc[today_race_X['horse_number'] == 16, 'horse_weight'] = sixteen
# today_race_X.loc[today_race_X['horse_number'] == 17, 'horse_weight'] = seventeen
# today_race_X.loc[today_race_X['horse_number'] == 18, 'horse_weight'] = eighteen

In [54]:
today_race_X = today_race_X.sort_values('horse_number')
today_race_X

,race_id,horse_id,rider_id,horse_number,age,sex,horse_weight,ground_status
0,202309020411,2018105081,1174,1,5,1,500,1
1,202309020411,2018100927,1115,2,5,1,500,1
3,202309020411,2016100915,1171,3,7,0,500,1
4,202309020411,2018102348,5203,4,5,0,500,1
5,202309020411,2018105074,1018,5,5,0,500,1
6,202309020411,2017105567,1088,6,6,0,500,1
7,202309020411,2019102879,660,7,4,0,500,1
8,202309020411,2019101782,5386,8,4,0,500,1
9,202309020411,2018100274,666,9,5,0,500,1
10,202309020411,2017105376,1163,10,6,0,500,1
2,202309020411,2019104740,5339,11,4,1,500,1
11,202309020411,2019105155,1180,12,4,0,500,1
12,202309020411,2018104963,1140,13,5,0,500,1
13,202309020411,2016104877,1126,14,7,0,500,1
14,202309020411,2016104851,1032,15,7,2,500,1
15,202309020411,2018100420,1102,16,5,0,500,1

In [55]:
#predict
train_baskets = today_race_X.groupby(["race_id"])["horse_id"].count().values
X = today_race_X.drop(["race_id", "horse_id"], axis=1)
y_pred = model.predict(X, group=train_baskets)

In [56]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
rank = np.arange(1, 19)
sorted_rank = rank[np.argsort(y_pred)[::-1]]

In [58]:
sorted_rank[0]

16